### ISSUE TITLE
Latest update points to a new repo

### ISSUE THREAD

**Issue by KatieMFritz** [carlcs/craft-footnotes#7]
Mainly leaving this here for other people! If you see versions 2.0.0 and later in your Craft Updates, note that Composer will actually install this repo instead: https://github.com/Vierbeuter/craft-footnotes

The setup is very different and you'll need to manually migrate your footnotes.

**Comment by carlcs** [comment]
Sorry about the confusion. The update that showed up in your Craft CP is from a completely different plugin, that you should not apply if you want to keep using this plugin here.

The root of the issue is that both plugins are using the same plugin handle `footnotes`, which the Craft plugin store is using to match plugins to repos. This wasn’t a problem until now because both plugins weren’t registered with the store, and in this case Craft update service doesn’t care about the handle and shows the releases from the matching Composer package name.

This changed in the moment @dueddel submitted their plugin https://github.com/Vierbeuter/craft-footnotes to the store. It became the one and only plugin with handle `footnotes`! 😎

I now went ahead and changed this plugin’s handle to `footnote`, so the plugin store accepts them as individual plugins. I also changed the package name to `carlcs/craft-footnote` and the repo name to `craft-footnote` to avoid further confusion.

To continue using the plugin and get on its “updates track” you need to update to 2.0.0 beta 5 by doing the following.

1. Uninstall the plugin in CP > Settings > Plugins
2. Install it again from the Plugin Store https://plugins.craftcms.com/footnote, or from the command line with the following commands.
    ```
    > composer require carlcs/craft-footnote:^2.0.0-beta.5
    > ./craft install/plugin footnote
    ```
3. Update the plugin handle in your custom Redactor configs
    ```
    "plugins": ["footnote"]
    ```

**Comment by dueddel** [comment]
Hi @carlcs, I'm sorry for any inconvenience being caused by my plugin! … Obviously you managed that issue professionally. 🤘 Great job!

My apologies also to you, @KatieMFritz.
Carl is absolutely right, I recently submitted my footnotes plugin to the Craft Plugin Store. Because of the same handle Craft is mixing things up a bit. Hope you didn't get into big trouble? 🖖

**Comment by dlindberg** [comment]
Out of curiosity, is there any chance of merging your efforts? Having presented the options to my content editors they'd like to be able to create notes using *both* methods. In some circumstances creating a short footnote on the fly and in other circumstances creating a much longer and more complex footnote by reference. Given the varying codebases and differing approaches this might not be possible. Though, explaining why me just installing both at the same time is a recipe for complete disaster has been an interesting challenge.

**Comment by dueddel** [comment]
Kinda good idea, @dlindberg. Up to now I had no closer look into the sources of carlcs' footnotes plugin and I never thought of something like that.
The problem here (at least my problem) is that I am currently out of time to do that. Also, to combine two things functioning in a totally different way is not very easy as you can sure imagine.
Maybe some day I can head against it. No promise, though. Sorry.

But hey, please be invited to do on your own and make some merge requests to either  carlcs/craft-footnote or vierbeuter/craft-footnotes. :)

Feel free to ask for help if you need some. I am pretty sure @carlcs will also be fine with that.

**Comment by dlindberg** [comment]
I'm somewhat time constrained at the moment as well and am a bit leery of forking and turning this into three nominally competing plugins. But I'll try and carve out some time to see if I see a path forward on such a project.

**Comment by carlcs** [comment]
Hey @dlindberg, I had a quick go on your suggested feature. Don’t have time for proper testing, so I’d appreciate if you could give feedback on it.

Install from `feature/inline-footnotes` branch, and then add `'inlineFootnoteMinLength' => 5` or something to your config/footnote.php

```json
{
  "require": {
    "carlcs/craft-footnote": "dev-feature/inline-footnotes"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/carlcs/craft-footnote"
    }
  ]
}
```

**Comment by dlindberg** [comment]
Thanks! It's in my project queue. My schedules have been upend in the last week, but working on the footnotes system in on the list for this week.

**Comment by carlcs** [comment]
@dlindberg the feature is now included in the latest release. Thank you for the suggestion.
